name: Muqi
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title

baseurl: "/SPhotos" # the subpath of your site, e.g. /blog
url: "https://sansuiz.github.io" # the base hostname & protocol for your site, e.g. http://example.com

gems: [jekyll-paginate] 
paginate: 5
paginate_path: "blog/page:num"
