name: "Picstory"
permalink: /Picstory/:year/:month/:day/:title.html

author: "Xunyi"
atom-baseurl: "https://xiangblq.github.io/Picstory/"
disqus: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /Picstory/archive.html
  - title: Tags
    class: fa fa-tags
    href: /Picstory/tags.html
  - title: About
    class: fa fa-user
    href: /Picstory/about.html
  - title: Gallery
    class: fa fa-film
    href: https://xiangblq.github.io/Picstory/
  - title: Subscribe
    class: fa fa-rss
    href: /Picstory/atom.xml

