name: "SPhotos"
permalink: /SPhotos/:year/:month/:day/:title.html

author: "SANSUI"
atom-baseurl: "https://sansuiz.github.io/SPhotos/"
disqus: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /SPhotos/archive.html
  - title: Tags
    class: fa fa-tags
    href: /SPhotos/tags.html
  - title: About
    class: fa fa-user
    href: /SPhotos/about.html
  - title: Gallery
    class: fa fa-film
    href: https://sansuiz.github.io/SPhotos/
  - title: Subscribe
    class: fa fa-rss
    href: /SPhotos/atom.xml

